image: node:22-alpine

stages:
  - lint
  - test

eslint:
  stage: lint
  script:
    - npm ci
    - npm run lint
  artifacts:
    reports:
      codequality: gl-codequality.json

jest:
  stage: test
  script:
    - npm ci
    - npm test